name: Build and deploy React app
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
      - name: Install dependencies
        run: npm install
      - name: Build the React app
        run: npm run build
      - name: Deploy to live branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git fetch origin main
          git checkout main

          mkdir ~/temp
          cp -r dist/{,.}* ~/temp

          git fetch origin live
          git checkout live

          rm -rf ./*
          cp -r ~/temp/{,.}* .

          git add -f .
          git status
          git commit -m "Deploy React app to live branch"
          
          git push origin live
